# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P8tJpEhNqpH8kQtkVGKk-KlsFGkD3RSu
"""

x=[int(i) for i in input('Enter the numbers:').split()]
print(sum(x))