# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P8tJpEhNqpH8kQtkVGKk-KlsFGkD3RSu
"""

def factorial(n):
  if n==0:
    return 1
  return n*factorial(n-1)
num=int(input('Enter a number:'))
print("Factorial of",num,"is",factorial(num))