# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P8tJpEhNqpH8kQtkVGKk-KlsFGkD3RSu
"""

a_dictionary = {"a": 26, "b": 35, "c": 10}

max_key = max(a_dictionary, key=a_dictionary.get)

print(max_key)