# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P8tJpEhNqpH8kQtkVGKk-KlsFGkD3RSu
"""

def decorators(fun):
	def deno(a,b):
		if a < b :
			a,b = b,a
		return fun(a,b)
	return deno
@decorators 
def div(a,b):
	return  a//b

a=int(input("Enter a number: "))
b=int(input("Enter a number: "))
print(a,b)


print(div(a,b))