# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P8tJpEhNqpH8kQtkVGKk-KlsFGkD3RSu
"""

def fun(n):
  return n % 3 == 0 and n % 5 == 0
# list from range (1, 100) 
li = list(range(1, 101))
print(list(filter (fun, li)))