# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P8tJpEhNqpH8kQtkVGKk-KlsFGkD3RSu
"""

word=input("Enter the word:")
letter=list(word)
count=0
pcount=0
big=0
for i in range(97,123):
  for j in range(0,len(letter)):
    if chr(i)==letter[j]:
      count+=1
      print('number of',chr(i),count,end='\n')
      if pcount<count:
        pcount=count
        big=chr(i)

  count=0
print('\n')
print(big,end='\n')